language: node_js
node_js:
- 0.8
- 0.1
env:
  secure:
    - N9Sdvbx2tGm5JppXAhF7PXS2AHqeNzpZ6zf+7MGO+MjuZoYs2tMAdt/aAHzpjrEO0nB8zUf11FMlvQQrNw4vpAIZ0Sa5GOfaewV88JIo6H3GM5LJ0IiI753vwO/+oH57AHa7yF+Ypf4aqONsPmeAWwGI1DTzxQtzaeuzPMACPl4=
    - BkRf427xcQbQi/IiDGMnIxeq7l+jKVAg6CWhyRFljd9FaWx8mtzYPib1LBV2CytuJYOqHIg5VvmMtJ5ULPLbEdHYA8sIsk/FhDfIjElhSiEplvKEcQREvukvBpCtPh+plp3/IE3C/woHuCVIC95+svspuGhfeiTfudGb4Mwb8sw=
